# Generated by Django 3.2.8 on 2021-12-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_accession', models.CharField(max_length=255)),
                ('bioproject', models.CharField(blank=True, max_length=255, null=True)),
                ('biosample', models.CharField(blank=True, max_length=255, null=True)),
                ('wgs_master', models.CharField(blank=True, max_length=255, null=True)),
                ('refseq_category', models.CharField(blank=True, max_length=255, null=True)),
                ('taxid', models.CharField(blank=True, max_length=255, null=True)),
                ('species_taxid', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('infraspecific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('isolate', models.CharField(blank=True, max_length=255, null=True)),
                ('version_status', models.CharField(blank=True, max_length=255, null=True)),
                ('assembly_level', models.CharField(blank=True, max_length=255, null=True)),
                ('release_type', models.CharField(blank=True, max_length=255, null=True)),
                ('genome_rep', models.CharField(blank=True, max_length=255, null=True)),
                ('seq_rel_date', models.CharField(blank=True, max_length=255, null=True)),
                ('asm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submitter', models.CharField(blank=True, max_length=255, null=True)),
                ('gbrs_paired_asm', models.CharField(blank=True, max_length=255, null=True)),
                ('paired_asm_comp', models.CharField(blank=True, max_length=255, null=True)),
                ('ftp_path', models.CharField(blank=True, max_length=255, null=True)),
                ('excluded_from_refseq', models.CharField(blank=True, max_length=255, null=True)),
                ('relation_to_type_material', models.CharField(blank=True, max_length=255, null=True)),
                ('asm_not_live_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Assembly Summary',
                'verbose_name_plural': 'Assembly Summaries',
                'ordering': ['organism_name', 'seq_rel_date'],
            },
        ),
        migrations.CreateModel(
            name='Prokaryotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_name', models.CharField(max_length=255)),
                ('taxid', models.CharField(blank=True, max_length=255, null=True)),
                ('bioproject_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=255, null=True)),
                ('gc', models.CharField(blank=True, max_length=255, null=True)),
                ('chromosome_refseq', models.CharField(blank=True, max_length=255, null=True)),
                ('chromosome_insdc', models.CharField(blank=True, max_length=255, null=True)),
                ('plasmids_refseq', models.CharField(blank=True, max_length=255, null=True)),
                ('plasmids_insdc', models.CharField(blank=True, max_length=255, null=True)),
                ('wgs', models.CharField(blank=True, max_length=255, null=True)),
                ('scaffolds', models.CharField(blank=True, max_length=255, null=True)),
                ('genes', models.CharField(blank=True, max_length=255, null=True)),
                ('bioproject_accession', models.CharField(blank=True, max_length=255, null=True)),
                ('proteins', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, max_length=255, null=True)),
                ('modify_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('biosample_accession', models.CharField(blank=True, max_length=255, null=True)),
                ('assembly_accession', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('ftp_path', models.CharField(blank=True, max_length=255, null=True)),
                ('pubmed_id', models.CharField(blank=True, max_length=255, null=True)),
                ('strain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
