# Generated by Django 3.2.8 on 2021-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblysummary',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
