# Generated by Django 3.2.8 on 2022-01-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0002_assemblysummary_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANI_report_prokaryotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genbank_accession', models.CharField(max_length=255)),
                ('refseq_accession', models.CharField(blank=True, max_length=255, null=True)),
                ('taxid', models.CharField(blank=True, max_length=255, null=True)),
                ('species_taxid', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('species_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assembly_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assembly_type_category', models.CharField(blank=True, max_length=255, null=True)),
                ('excluded_from_refseq', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_type_assembly', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_type_organism_name', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_type_category', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_type_ANI', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_type_gcoverage', models.CharField(blank=True, max_length=255, null=True)),
                ('declared_type_scoverage', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_type_assembly', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_species_taxid', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_species_name', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_type_category', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_type_ANI', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_type_gcoverage', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_type_scoverage', models.CharField(blank=True, max_length=255, null=True)),
                ('best_match_status', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy_check_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
