# Generated by Django 3.2.8 on 2022-01-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomes', '0003_ani_report_prokaryotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ani_report_prokaryotes',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
